[DEFAULT]
# IMPORTANT: The raison d'être for this INI file is that some models from the Dynawo library 
# do not have a few parameters needed by DyCoV tests, and therefore they can only be provided here, 
# instead of Producer.PAR. However, there are other Dynawo models that do have one or more of 
# the parameters listed here in this INI. In such case, you will have to make sure you provide said 
# parameters in **both** input files, Parameter.INI and Parameter.PAR. DyCoV will double-check for 
# you that the values are the same, and stop with an ERROR if they are not.

# p_{max_unite} injection as defined by the DTR in MW (expected value >= 0.0)
p_max_injection = 75
# u_nom is the nominal voltage in the PDR Bus (in kV)
# Allowed values: 400, 225, 150, 90, 63 (land) and 132, 66 (offshore)
u_nom = 225
# q_max is the maximum reactive power of all generating units (in MVar)
q_max = 40
# q_min is the minimum reactive power of all generating units (in MVar)
q_min = -40
# topology
topology = S+Aux
# Active power sharing per generator unit (fraction). Values must be between 0.0 and 1.0
P_sharing_Wind_Turbine = 1.0
# Reactive power sharing per generator unit (fraction). Values must be between 0.0 and 1.0
Q_sharing_Wind_Turbine = 1.0
