[DEFAULT]
# IMPORTANT: The raison d'être for this INI file is that some models from the Dynawo library 
# do not have a few parameters needed by DyCoV tests, and therefore they can only be provided here, 
# instead of Producer.PAR. However, there are other Dynawo models that do have one or more of 
# the parameters listed here in this INI. In such case, you will have to make sure you provide said 
# parameters in **both** input files, Parameter.INI and Parameter.PAR. DyCoV will double-check that 
# INI values are more restrictive than PAR values, and stop with an ERROR if they are no.

# p_{max_unite} injection as defined by the DTR in MW (expected value >= 0.0)
p_max_injection_in_PDR = 40
# p_{max_unite} consumption as defined by the DTR in MW (only for BESS, expected value >= 0.0).
p_max_consumption_in_PDR = 40
# u_nom is the nominal voltage in the PDR Bus (in kV)
# Allowed values: 400, 225, 150, 90, 63 (land) and 132, 66 (offshore)
u_nom_in_PDR = 225
# q_max is the maximum reactive power in the PDR Bus (in MVar)
q_max_in_PDR = 13
# q_min is the minimum reactive power in the PDR Bus (in MVar)
q_min_in_PDR = -13
# topology
topology = S
# Active power sharing per generator unit (fraction). Values must be between 0.0 and 1.0
P_sharing_Bess = 1.0
# Reactive power sharing per generator unit (fraction). Values must be between 0.0 and 1.0
Q_sharing_Bess = 1.0
