[ControlModes]
USetpoint_WECC_Plant = WTG_UControl_Local_Coordinated,WTG_Only_UControl
QSetpoint_WECC_Plant = WTG_QControl_Local_Coordinated,WTG_Only_QControl
PSetpoint_WECC_Plant = WTG_PControl_Oscillation,WTG_PControl
VoltageDroop_WECC_Plant = WTG_Voltage_Droop

USetpoint_WECC_Turbine = WT_UControl
QSetpoint_WECC_Turbine = WT_Local_Coordinated,WT_QControl
PSetpoint_WECC_Turbine = WT_PControl_Oscillation,WT_PControl

USetpoint_IEC_Plant = IECWPP_ReactivePowerControl_UQStatic,IECWPP_ReactivePowerControl_UControl,IECWPP_Openloop_UQStatic,IECWPP_Openloop_UControl,IECWPP_VoltageControl_UQStatic,IECWPP_VoltageControl_UControl
QSetpoint_IEC_Plant = IECWPP_ReactivePowerControl_QReference,IECWPP_Openloop_ReactivePowerControl_QReference
PSetpoint_IEC_Plant = 
VoltageDroop_IEC_Plant = IECWPP_Voltage_Droop

USetpoint_IEC_Turbine = IECWT_VoltageControl
QSetpoint_IEC_Turbine = IECWT_ReactivePowerControl,IECWT_Openloop_ReactivePowerControl
PSetpoint_IEC_Turbine = 

# WECC Plant Voltage Droop
[WTG_Voltage_Droop]
RefFlag = True
VCompFlag = False

# WECC Plant Control Modes
[WTG_UControl_Local_Coordinated]
PfFlag = False
VFlag = True
QFlag = True
RefFlag = True

[WTG_QControl_Local_Coordinated]
PfFlag = False
VFlag = True
QFlag = True
RefFlag = False

[WTG_Only_UControl]
PfFlag = False
QFlag = False
RefFlag = True

[WTG_Only_QControl]
PfFlag = False
QFlag = False
RefFlag = False

[WTG_PControl]
PFlag = False
FreqFlag = True

[WTG_PControl_Oscillation]
PFlag = True
FreqFlag = True

# WECC Turbine Control Modes
[WT_Local_Coordinated]
PfFlag = False
VFlag = True
QFlag = True

[WT_UControl]
PfFlag = False
VFlag = False
QFlag = True

[WT_QControl]
PfFlag = False
QFlag = False

[WT_PControl]
PFlag = False

[WT_PControl_Oscillation]
PFlag = True

# IEC Plant Voltage Droop
[IECWPP_Voltage_Droop]
MqG = 0
MwpqMode = 3

# IEC Plant Control Modes
# naming pattern: ModelFamily_InverterLevelMode_PlantLevelMode
[IECWPP_ReactivePowerControl_UQStatic]
MqG = 1
MwpqMode = 2

[IECWPP_ReactivePowerControl_UControl]
MqG = 1
MwpqMode = 3

[IECWPP_Openloop_UQStatic]
MqG = 2
MwpqMode = 2

[IECWPP_Openloop_UControl]
MqG = 2
MwpqMode = 3

[IECWPP_VoltageControl_UQStatic]
MqG = 0
MwpqMode = 2

[IECWPP_VoltageControl_UControl]
MqG = 0
MwpqMode = 3

[IECWPP_ReactivePowerControl_QReference]
MqG = 1
MwpqMode = 0

[IECWPP_Openloop_ReactivePowerControl_QReference]
MqG = 2
MwpqMode = 0

[IECWPP_PowerFactorControl_PfReference]
MqG = 3
MwpqMode = 1

[IECWPP_Openloop_PowerFactorControl_PfReference]
MqG = 4
MwpqMode = 1

# IEC Turbine Control Modes
# naming pattern: ModelFamily_InverterLevelMode
[IECWT_VoltageControl]
MqG = 0

[IECWT_ReactivePowerControl]
MqG = 1

[IECWT_Openloop_ReactivePowerControl]
MqG = 2

[IECWT_PowerFactorControl]
MqG = 3

[IECWT_Openloop_PowerFactorControl]
MqG = 4

