#[LoadPQ] ==> Temporarily disabled until Issue 58 is resolved
#ActivePower0 = load_P0Pu # base SnRef
#ReactivePower0 = load_Q0Pu # base SnRef
#Voltage0 = load_U0Pu # base UNom
#Phase0 = load_UPhase0
#ActivePower = load_PPu # base SnRef
#ReactivePower = load_QPu # base SnRef
#ActiveCurrent = load_terminal_i_re
#ReactiveCurrent = load_terminal_i_im

[LoadAlphaBeta]
ActivePower0 = load_P0Pu # base SnRef
ReactivePower0 = load_Q0Pu # base SnRef
Voltage0 = load_U0Pu # base UNom
Phase0 = load_UPhase0
ActivePower = load_PPu # base SnRef
ReactivePower = load_QPu # base SnRef
ActiveCurrent = load_terminal_i_re
ReactiveCurrent = load_terminal_i_im
Alpha = load_alpha
Beta = load_beta