[DEFAULT]
# p_{max_unite} injection as defined by the DTR in MW (expected value >= 0.0)
p_max_injection = 110
# p_{min_unite} injection in MW
p_min_injection = -110
# u_nom is the nominal voltage at the PDR bus (in kV)
# Allowed values: 400, 225, 150, 90, 63 (land) and 132, 66 (offshore)
u_nom = 225
# q_max is the maximum reactive power of all generating units (in MVar)
q_max = 40
# q_min is the minimum reactive power of all generating units (in MVar)
q_min = -40

[GFM Parameters]
# This Section contains input parameters required when calculating Grid-Forming envelope curves (`dycov generateEnvelopes`)
# Note that some other parameters such as u_nom, p_max, p_min, etc. need to be defined above in the general section.

# Nominal apparent power (Warning: if you run Dynawo simulations, DyCoV will use the Snom specified in the PAR file, not this one) 
Snom = 90.0

# Damping factor (Variant)
D = 152.0

# Inertia constant (Variant)
H = 2.0

# Effective reactance
# Updated to 0.27 pu as per Fiche 118 Section 5 
Xeff = 0.27