#!/usr/bin/env python3
# -*- coding: utf-8 -*-
SIMULATION_START_TIME_DEFAULT = 0.0
SIMULATION_START_TIME_EXTENDED = -1.0
SIMULATION_END_TIME = 5.0
SIMULATION_POINTS = 3000
SIMULATION_EVENT_TIME = 0.0

EMT_FINAL_DELAY_S = 0.02
SCR_BOUND_DELAY_S = 0.01
OVERDAMPED_MAX_DELAY_S = 0.01
UNDERDAMPED_MIN_DELAY_S = 0.01
UNDERDAMPED_MAX_DELAY_S = 0.01

SCRJUMP_INITIAL_LIMITING_S = 0.1
SCRJUMP_MODIFY_ENVELOPE_S = 0.03

TIME_TUNNEL_START_OFFSET = 0.02
TIME_TUNNEL_EXP_TAU = 0.3
