name: Dev CI

on:
  pull_request:

jobs:
  build:

    name: Build OS ${{ matrix.os}} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build setuptools wheel
          python -m pip install --upgrade flake8 pytest pytest-cov

      - name: Build package
        run: python -m build --wheel

      - name: Install wheel
        if: matrix.os != 'windows-latest'
        run: pip install dist/*.whl

      - name: Install wheel
        if: matrix.os == 'windows-latest'
        shell: bash
        run: python -m pip install dist/*.whl

      - name: Linting with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 src --count --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 99 chars wide
          flake8 src --count --exit-zero --statistics --max-complexity=10 
          
      # - name: Run tests
      #   run: pytest

      - name: Generate coverage
        run: pytest --cov=. --cov-report=xml 

      #- name: Sonar analysis
      #  uses: sonarsource/sonarcloud-github-action@v2.0.2
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #  with:
      #    args: |
      #      -Dsonar.python.coverage.reportPaths=coverage.xml

