name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'  # Triggered when you push a tag that starts with 'v', such as v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python3 -m pip install --upgrade pip build setuptools wheel

      - name: Build package
        run: python3 -m build --sdist --wheel

      - name: Upload package to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            LICENSE
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}